name: Build and Publish
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: :composeApp:wasmJsBrowserDistribution

      - name: Deploy browser app
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: composeApp/build/dist/wasmJs/productionExecutable
          clean: true
